on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the release, should match an existing tag name. E.g. v0.1.0"
        required: true

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo build --release

      # upload to release
      - run: gh release upload ${{ inputs.version }} target/release/defect.exe
        if: ${{ matrix.os == 'windows-latest' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: gh release upload ${{ inputs.version }} target/release/defect
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
