on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the release, should match an existing tag name. E.g. v0.1.0"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            artifact: defect-x86_64
            extension: ""
          - target: aarch64-unknown-linux-musl
            artifact: defect-aarch64
            extension: ""
          - target: x86_64-pc-windows-gnu
            artifact: defect-x86_64
            extension: ".exe"
    steps:
      - uses: actions/checkout@v4

      - uses: DiscreteTom/setup-rust-cross@v0.1.1

      - name: Build for ${{ matrix.target }}
        run: |
          cross build --release --target ${{ matrix.target }}

      - name: Rename artifact
        run: |
          mv target/${{ matrix.target }}/release/defect${{ matrix.extension }} target/${{ matrix.target }}/release/${{ matrix.artifact }}${{ matrix.extension }}

      - name: Upload artifact to release
        run: gh release upload ${{ inputs.version }} target/${{ matrix.target }}/release/${{ matrix.artifact }}${{ matrix.extension }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
