on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the release, should match an existing tag name. E.g. v0.1.0"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DiscreteTom/setup-rust-cross@v0.1.1

      - run: |
          cross build --release --target x86_64-unknown-linux-musl
          mv target/x86_64-unknown-linux-musl/release/defect target/x86_64-unknown-linux-musl/release/defect-x86_64
      - run: |
          cross build --release --target aarch64-unknown-linux-musl
          mv target/aarch64-unknown-linux-musl/release/defect target/aarch64-unknown-linux-musl/release/defect-aarch64
      - run: |
          cross build --release --target x86_64-pc-windows-gnu
          mv target/x86_64-pc-windows-gnu/release/defect.exe target/x86_64-pc-windows-gnu/release/defect-x86_64.exe

      - run: |
          gh release upload ${{ inputs.version }} target/x86_64-unknown-linux-musl/release/defect-x86_64
          gh release upload ${{ inputs.version }} target/aarch64-unknown-linux-musl/release/defect-aarch64
          gh release upload ${{ inputs.version }} target/x86_64-pc-windows-gnu/release/defect-x86_64.exe
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
